### ISSUE TITLE
Grade first homework

### ISSUE THREAD

**Issue by jjohnst6260** [jjohnst6260/astr-119#2]
@julesfowler will you please grade my homework? I'm not sure that I performed the pull request properly, though.

**Comment by julesfowler** [comment]
Hey @jjohnst6260 -- it does look like something went awry with this assignment. Your repository doesn't have any new files and there's no record of a pull request on this repo. Can you try `git push`-ing your assignment from your local machine, and then opening a pull request through the GitHub website?
